services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: pharmatrack-api
    networks:
      - pharmatrack-network
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: pharmatrack-web
    networks:
      - pharmatrack-network
    depends_on:
      - api
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:15-alpine
    container_name: pharmatrack-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pharmatrack-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pharmatrack -d pharmatrack"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:

networks:
  pharmatrack-network:
    driver: bridge
