services:
  api:
    build:
      target: production
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    environment:
      - PYTHONPATH=/app
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  web:
    build:
      target: production
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  db:
    env_file:
      - .env.prod
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
