services:
  api:
    build:
      target: development
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./api:/app
      - /app/__pycache__
    command:
      ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped

  web:
    build:
      target: development
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    command: ["npm", "run", "dev"]
    restart: unless-stopped

  db:
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    restart: unless-stopped
